version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 126511412377.dkr.ecr.us-east-1.amazonaws.com 

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker-compose build .
      - docker tag ecs-example:latest 126511412377.dkr.ecr.us-east-1.amazonaws.com/ecs-example:latest

  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 126511412377.dkr.ecr.us-east-1.amazonaws.com/ecs-example:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "ecs-example" "126511412377.dkr.ecr.us-east-1.amazonaws.com/ecs-example" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    
